name: Super Simple Test

on:
  push:

jobs:
  my-first-job:
    runs-on: ubuntu-latest
    
    steps:
      - name: Say Hello
        run: echo "這是一個超簡單的測試任務！"

      - name: Check Node Version
        run: node -v